services:
  mysql:
    image: mysql:8.0
    container_name: tapestria-db
    restart: always
    environment:
      MYSQL_DATABASE: tapestria
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: tapestria-backend
    depends_on:
      - mysql
        # condition: service_healthy
      - recommender
        # condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tapestria-db:3306/tapestria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: tapestria-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  recommender:
    build: ./recommender
    container_name: tapestria-recommender
    ports:
      - "5000:5000"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql

volumes:
  db_data:
